Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2024
Var

   x, soma: inteiro

Inicio

   Escreva("Digite o primeiro número: ")
   leia(x)

   enquanto (x <> 0) faca
      Escreva("Digite outro número: ")
      leia(x)
   fimenquanto
   

Fimalgoritmo